//  Group 47
//  2016B3A70562P   Akash Kabra
//  2016B3A70523P   Ayush Mungad
//  2016B4A70520P   Kumar Anant Raj
//  2016B4A70533P   Mustansir Mama
//  2016B5A70715P   Bhavesh Chand

#include "langSpec.h"

//  Provide strings corresponding to each keyword. Used by lexer
keyword keyword_mapping[]={
    {"integer",INTEGER},
    {"real",REAL},
    {"boolean",BOOLEAN},
    {"of",OF},
    {"array",ARRAY},
    {"start",START},
    {"end",END},
    {"declare",DECLARE},
    {"module",MODULE},
    {"driver",DRIVER},
    {"program",PROGRAM},
    {"record",RECORD},
    {"tagged",TAGGED},
    {"union",UNION},
    {"get_value",GET_VALUE},
    {"print",PRINT},
    {"use",USE},
    {"with",WITH},
    {"parameters",PARAMETERS},
    {"true",TRUE},
    {"false",FALSE},
    {"takes",TAKES},
    {"input",INPUT},
    {"returns",RETURNS},
    {"AND",AND},
    {"OR",OR},
    {"for",FOR},
    {"in",IN},
    {"switch",SWITCH},
    {"case",CASE},
    {"break",BREAK},
    {"default",DEFAULT},
    {"while",WHILE}
};

// Provide strings corresponding to each token in order. Used to automate grammar and label nodes in ParseTree
char* terminal_list[] = {
    "PLUS", 
    "MINUS", 
    "MUL",
    "DIV",
    "LT", 
    "LE", 
    "GE", 
    "GT", 
    "EQ", 
    "NE", 
    "DEF", 
    "ENDDEF",
    "COLON",
    "RANGEOP",
    "SEMICOL",
    "COMMA",
    "ASSIGNOP",
    "SQBO",
    "SQBC",
    "BO",
    "BC",
    "DRIVERDEF",
    "DRIVERENDDEF",
    "INTEGER",
    "REAL",
    "BOOLEAN",
    "OF",
    "ARRAY",
    "START",
    "END",
    "DECLARE",
    "MODULE",
    "DRIVER",
    "PROGRAM",
    "RECORD",
    "TAGGED",
    "UNION",
    "GET_VALUE",
    "PRINT",
    "USE",
    "WITH",
    "PARAMETERS",
    "TRUE",
    "FALSE",
    "TAKES",
    "INPUT",
    "RETURNS",
    "AND",
    "OR",
    "FOR",
    "IN",
    "SWITCH",
    "CASE",
    "BREAK",
    "DEFAULT",
    "WHILE",
    "ID",
    "NUM",
    "RNUM", 
    "EPS",
    "$"
};

// Provide strings corresponding to each non-terminal in order. Used to automate grammar and label nodes in ParseTree
char* non_terminal_list[] = {
	"program",
	"moduleDeclarations",
	"moduleDeclaration",
	"otherModules",
	"driverModule",
	"module",
	"ret",
	"input_plist",
	"N1",
	"output_plist",
	"N2",
	"dataType",
	"range_arrays",
	"type",
	"moduleDef",
	"statements",
	"statement",
	"ioStmt",
	"boolConstt",
	"var_id_num",
	"var",
	"whichId",
	"simpleStmt",
	"assignmentStmt",
	"whichStmt",
	"lvalueIDStmt",
	"lvalueARRStmt",
	"index1",
	"moduleReuseStmt",
	"optional",
    "idList",
	"N3",
	"expression",
	"U",
	"new_NT",
	"unary_op",
	"arithmeticOrBooleanExpr",
	"N7",
	"AnyTerm",
	"N8",
	"arithmeticExpr",
	"N4",
	"term",
	"N5",
	"factor",
	"op1",
	"op2",
	"logicalOp",
	"relationalOp",
	"declareStmt",
	"condionalStmt",
	"caseStmts",
	"N9",
	"value",
	"default1",
	"iterativeStmt",
	"range"
};


